### PR TITLE
 Task TG-269 for US TG-243

### PR DESCRIPTION
**Pull request by rkhatta1**
**Files Added/Changed:**
1. Dashboard.js
2. TaskCouplingMetricVisualization.js
3. taiga-service.js

--> Plugged the UI for Task Coupling in the Dashboard.
--> Tested the API calls and visualization of Task Coupling.

**Photo:**

Screenshot 2024-04-19 145302

### CODE REVIEW

**Review by isingh27 — CHANGES_REQUESTED** [review]
Everything looks perfect but can you please change the color scheme to blue and white

**Comment by rkhatta1** [comment]
> Everything looks perfect but can you please change the color scheme to blue and white

Added a new US for UI cleanup after the MVP is delivered.

**Review by isingh27 — APPROVED** [review]
LGTM!

**Review by dpate258 — APPROVED** [review]
LGTM!

**Pull request merged**
