### PR TITLE
[TASK TG-263- for US TG-262] "added Redis cache container for burndow…

### PR DESCRIPTION
**Pull request by avijay48**
…n service"

### CODE REVIEW

**Review by jvaida — CHANGES_REQUESTED** [review]
As per our architecture diagram, redis should be in the same container as the burndown service & not a different container of its own.

**Review by rkhatta1 — APPROVED** [review]
LGTM!

**Comment by avijay48** [comment]
> As per our architecture diagram, redis should be in the same container as the burndown service & not a different container of its own.

I have made the changes

**Review by jvaida — APPROVED** [review]
LGTM!

**Pull request merged**
